function nmap(keys, fn, desc) vim.keymap.set("n", keys, fn, { desc = desc }) end

nmap("<C-s>", "<cmd>write<cr>", "Save current buffer")
nmap("<f1>", "<cmd>FindHelp<cr>", "Find help")
nmap("<leader>e", "<cmd>NeoTreeFloatToggle<cr>", "[E]xplore")
nmap("<leader>E", "<cmd>Oil<cr>", "[E]xplore")
nmap("<leader>gg", "<cmd>Neogit kind=tab<cr>", "git")
nmap("<leader>s/", "<cmd>Telescope builtin<cr>", "available")
nmap("<leader>s`", "<cmd>Telescope marks<cr>", "marks")
nmap("<leader>sb", "<cmd>Buffers<cr>", "buffers")
nmap("<leader>sc", "<cmd>Telescope commands<cr>", "commands")
nmap("<leader>sd", "<cmd>Telescope diagnostics<cr>", "diagnostics")
nmap("<leader>sf", "<cmd>FindFiles<cr>", "find files")
nmap("<leader>sg", "<cmd>LiveGrep<cr>", "live grep")
nmap("<leader>sh", "<cmd>FindHelp<cr>", "help tags")
nmap("<leader>sl", "<cmd>LOC<cr>", "loclist")
nmap("<leader>sm", "<cmd>ManPages<cr>", "man pages")
nmap("<leader>sq", "<cmd>QF<cr>", "quickfix")
nmap("<leader>ss", "<cmd>Symbols<cr>", "symbols")
nmap("<leader>st", "<cmd>Telescope treesitter<cr>", "treesitter")
nmap("<leader>sw", "<cmd>GrepByWord<cr>", "grep by word")
nmap("<leader>zc", function() vim.opt.conceallevel = vim.opt.conceallevel:get() == 0 and 2 or 0 end, "conceal")
nmap("<leader>zn", function() vim.opt.number = not vim.opt.number:get() end, "number")
nmap("<leader>zr", function() vim.opt.ruler = not vim.opt.ruler:get() end, "ruler")
nmap("<leader>zs", function() vim.opt.spell = not vim.opt.spell:get() end, "spell")
nmap("<leader>zw", function() vim.opt.wrap = not vim.opt.wrap:get() end, "wrap")
nmap("<leader>zl", function() vim.opt.list = not vim.opt.list:get() end, "list")
nmap("<leader>zp", function() vim.opt.paste = not vim.opt.paste:get() end, "paste")
nmap("<leader>so", "<cmd>lua require'spread'.out({silent = true})<cr>", "spread")
nmap("<leader>sc", "<cmd>lua require'spread'.combine({silent = true})<cr>", "combine")
