function nmap(keys, fn, desc) vim.keymap.set("n", keys, fn, { desc = desc }) end

nmap("<leader>e", "<cmd>NeoTreeFloatToggle<cr>", "[E]xplore")
nmap("<leader>sf", "<cmd>FindFiles<cr>", "find files")
nmap("<leader>sh", "<cmd>FindHelp<cr>", "help tags")
nmap("<leader>sw", "<cmd>GrepByWord<cr>", "grep by word")
nmap("<leader>sg", "<cmd>LiveGrep<cr>", "live grep")
nmap("<leader>sb", "<cmd>Buffers<cr>", "buffers")
nmap("<leader>sm", "<cmd>ManPages<cr>", "man pages")
nmap("<leader>sq", "<cmd>QF<cr>", "quickfix")
nmap("<leader>sl", "<cmd>LOC<cr>", "loclist")
nmap("<leader>ss", "<cmd>Symbols<cr>", "symbols")
nmap("<leader>sd", "<cmd>Telescope diagnostics<cr>", "diagnostics")
nmap("<leader>sc", "<cmd>Telescope commands<cr>", "commands")
nmap("<leader>s`", "<cmd>Telescope marks<cr>", "marks")
nmap("<leader>s/", "<cmd>Telescope builtin<cr>", "available")
nmap("<leader>st", "<cmd>Telescope treesitter<cr>", "treesitter")
nmap("<leader>gg", "<cmd>Neogit kind=tab<cr>", "git")
