if vim.g._core_options_applied then return end
vim.g._core_options_applied = true

local opt = vim.opt
opt.autoread = true
opt.inccommand = "split"
opt.shada = { "'10", "<0", "s10", "h" }
opt.backspace:append { "nostop" }
opt.backupdir:remove "."
opt.clipboard = "unnamedplus"
opt.cmdheight = 0
opt.completeopt = { "menuone", "noselect" }
opt.conceallevel = 2
opt.confirm = true
opt.copyindent = true
opt.cursorline = true
opt.expandtab = true
opt.exrc = true
vim.o.fileencoding = "utf-8"
opt.fillchars = { eob = " " }
opt.foldenable = false
opt.foldexpr = "nvim_treesitter#foldexpr()"
opt.foldlevel = 0
opt.foldmethod = "expr"
opt.formatoptions:remove { "o" }
opt.history = 100
opt.ignorecase = true
opt.laststatus = 3
opt.linebreak = true
opt.list = true
opt.listchars.extends = "⟩"
opt.listchars.precedes = "⟨"
opt.listchars.tab = "│→"
opt.listchars.trail = "·"
opt.sessionoptions.blank = false
opt.sessionoptions.buffers = false
opt.sessionoptions.curdir = true
opt.sessionoptions.folds = true
opt.sessionoptions.globals = false
opt.sessionoptions.help = true
opt.sessionoptions.localoptions = true
opt.sessionoptions.skiprtp = true
opt.sessionoptions.tabpages = true
opt.sessionoptions.terminal = true
opt.sessionoptions.winpos = true
opt.sessionoptions.winsize = true
opt.listchars.nbsp = "␣"
opt.mouse = "a"
opt.mousemoveevent = true
opt.number = true
opt.preserveindent = true
opt.pumheight = 10
opt.pyxversion = 3
opt.relativenumber = false
opt.scrolljump = 1
opt.scrolloff = 8
opt.secure = true
opt.shiftwidth = 2
opt.shortmess.I = true
opt.shortmess.s = true
opt.showbreak = "↪ "
opt.showmode = false
opt.showtabline = 2
opt.sidescrolloff = 8
opt.signcolumn = "yes:2"
opt.smartcase = true
opt.spell = false
opt.spellfile = vim.fn.stdpath "config" .. "/spell/en.utf-8.add"
opt.splitbelow = false
opt.splitright = true
opt.tabstop = 2
opt.termguicolors = true
opt.thesaurus = vim.fn.stdpath "config" .. "/spell/thesaurus.txt"
opt.timeout = true
opt.timeoutlen = 300
opt.title = true
opt.titlestring = "%f // nvim"
opt.undofile = true
opt.updatetime = 300
opt.wildmenu = true
opt.wrap = false
opt.writebackup = false

if vim.g.neovide then
  opt.guifont = "Monaspace Neon NF:h13"
  vim.g.neovide_cursor_animate_in_insert_mode = false
  vim.g.neovide_refresh_rate_idle = 5
  vim.g.neovide_scale_factor = 1.0
  vim.g.neovide_cursor_animation_length = 0.0
  vim.g.neovide_cursor_antialiasing = true
  vim.g.neovide_confirm_quit = false
  vim.g.neovide_cursor_short_animation_length = 0.0
  vim.g.neovide_cursor_trail_size = 0.01
  vim.g.neovide_cursor_vfx_mode = ""
  vim.g.neovide_scroll_animation_length = 0.0
  vim.g.neovide_position_animation_length = 0.0
  vim.g.neovide_hide_mouse_when_typing = true
  vim.g.neovide_refresh_rate = 60
  vim.g.neovide_padding_bottom = 0
  vim.g.neovide_padding_left = 1
  vim.g.neovide_padding_right = 0
  vim.g.neovide_remember_window_size = true
  vim.g.neovide_profiler = false
  vim.g.neovide_cursor_smooth_blink = true
  vim.g.neovide_padding_top = 1
  vim.g.neovide_show_border = false
  vim.g.neovide_opacity = 0.95
  vim.g.neovide_window_blurred = true
end

vim.g.treesitter_parsers_dir = vim.fn.stdpath "data" .. "/parsers"
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.autoformat_enabled = false
vim.g.inlay_hints_enabled = true
vim.g.cmp_enabled = true
vim.g.matchup_matchparen_deferred = 1
vim.g.autopairs_enabled = true
vim.g.diagnostics_enabled = true
vim.g.loaded_ruby_provider = false
vim.g.loaded_perl_provider = false
vim.g.icons = true
